AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.travelease.travelease.LambdaHandler::handleRequest
      Runtime: java17
      CodeUri:
        S3Bucket: travelease
        S3Key: travelease-0.0.1-SNAPSHOT.war
      MemorySize: 512
      Timeout: 30
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
